export const DOCS_CONFIG = {
  RECORD_PER_PAGE: 12,
  RECORD_URL_PREFIX: process.env.NEXT_PUBLIC_RECORD_URL_PREFIX || "general",
  RECORD_SUBSTR_BASIC_NUMBER: 80,
  RECORD_SUBSTR_NAVBAR_NUMBER: 24,
  PAGE_RECOMMEND_COUNT: 6,
  MENU_SORT_BY: process.env.NEXT_PUBLIC_MENU_SORT_BY || "notion",
  PSEUDO_STATIC: process.env.NEXT_PUBLIC_PSEUDO_STATIC || false,
};
